### ISSUE TITLE
Authelia clients override eachother

### ISSUE THREAD

**Issue by sivertism** [ibizaman/selfhostblocks#126]
## Issue

The authelia OIDC clients each get written to their own yaml files, and Authelia is launched with
`authelia --config config.yaml,client1.yaml,client2.yaml,client3.yaml`

However, it seems like authelia reads the yamls as if they were all in the same file, meaning that each OIDC client overrides the previous one because each client defines the sequence `identity_providers.oidc.clients`. I.e. Authelia doesn't implement any merging logic (like nix does).

I've checked that this is the case by removing one and one OIDC client from my SHB config, and checking that only the last one works. (tested through openidconnect.net, and by checking the authelia debug log, which prints registered clients).

The solution would probably be to write out one `clients.yaml` file containing all clients instead of one file per client.

**Comment by ibizaman** [comment]
Oh that's a shame. But it should be easy to fix thanks to nix. Thanks for the report!
