### ISSUE TITLE
Jellyfin service missing some directories

### ISSUE THREAD

**Issue by sivertism** [ibizaman/selfhostblocks#163]
No big deal, but thought I'd file this here so we remember to fix it at some point.

There are two missing directories preventing successful start of the jellyfin service when running on a fresh install.

`/var/lib/jellyfin/config`
`/var/lib/jellyfin/plugins/configurations`

For anyone who might run into this, you can get around it with

```console
> sudo mkdir -p /var/lib/jellyfin/config
> sudo mkdir -p /var/lib/jellyfin/plugins/configurations
> sudo chown -R jellyfin:jellyfin  /var/lib/jellyfin
```

**Comment by ibizaman** [comment]
FYI the way to solve this in NixOS is to use [systemd.tmpfiles.d.rules](https://search.nixos.org/options?channel=23.11&show=systemd.tmpfiles.rules&from=0&size=50&sort=relevance&type=packages&query=tmpfiles.d) option whose accepted values are defined here https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html

There are a few examples in this repo too.

Thank you for the report! :)

**Comment by ibizaman** [comment]
I'm not sure what fixed this but adding those directories manually is not needed in the [NixOS tests](/nix/store/amxd2p02wx78nyaa4bkb0hjvgwhz1dq7-source). I'll close it for now but feel free to reopen.
